title: dmitrydao blog
author: Dmitry Baimuratov
email: dmitrydaopro@gmail.com
description: Tech Writer. Steem Witness
url: "https://dmitrydao.github.io" 

# Build settings
remote_theme: huangyz0918/moving
# theme: moving
plugins:
  - jekyll-feed

moving:
  about_you: Devs Code. I write.
  date_format: "%b %d"
  back_to: "Back to"
  social_links:
    github:  dmitrydao
    twitter:  dmitrydao
    linkedin: dmitrydao

